export const HTTP_STATUS = {
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  INTERNAL_SERVER_ERROR: 500,
};

export const RESPONSE_CODE = {
  USERNAME_OR_PASSWORD_REQUIRED: 'USERNAME_OR_PASSWORD_REQUIRED',
};